"""Independent saved-probe prediction, optimality and split reconstruction."""
import argparse,json
from pathlib import Path
import numpy as np
from adaptation_streams import sha


def main():
    p=argparse.ArgumentParser()
    for k in ('run','cache','horizon','protocol'):p.add_argument('--'+k,required=True)
    a=p.parse_args();d=Path(a.run);r=json.loads((d/'report.json').read_text());assert r['source_sha256']==sha(Path(__file__).with_name('fit_motion_probe_feasibility.py')) and r['protocol_sha256']==sha(a.protocol);checks=[]
    for b in r['bindings']:
        g=b['group'];cd=Path(a.cache)/f'job_{2*g}';hd=Path(a.horizon)/f'job_{g}'
        assert sha(cd/'report.json')==b['cache_report_sha256'] and sha(cd/'acceptance.json')==b['cache_acceptance_sha256'] and sha(hd/b['head_file'])==b['head_sha256']
        h=dict(np.load(hd/b['head_file']));features={};targets={};ids={}
        for split in ('train','validation'):
            assert sha(cd/('planner_'+split+'.npz'))==b[split+'_sha256'];z=np.load(cd/('planner_'+split+'.npz'));obs=z['observed'][:,1:4].astype(float);v=(obs-h['mean'])/h['scale']
            for k in (0,2,4):
                v=v@h[f'{k}.weight'].astype(float).T+h[f'{k}.bias']
                if k!=4:v=np.maximum(v,0)
            v=v*h['target_scale']+h['target_mean'];raw=z['raw_states'][:,1:4];true=np.concatenate([raw[:,:,:4],np.sin(raw[:,:,4:5]),np.cos(raw[:,:,4:5])],axis=-1)
            features[split]=dict(latent_current=obs[:,-1],latent_history=obs.reshape(len(obs),576),decoded_pose_history=v.reshape(len(obs),18),true_pose_history=true.reshape(len(obs),18));targets[split]=z['raw_states'][:,3,5:7];ids[split]=z['identities'][:,2]
        assert not set(ids['train'])&set(ids['validation'])
        for name,fp in b['artifacts'].items():
            assert sha(d/fp['file'])==fp['sha256'];w=np.load(d/fp['file']);x=features['train'][name];y=targets['train'];np.testing.assert_allclose(w['mean'],x.mean(0),rtol=0,atol=0);np.testing.assert_array_equal(w['intercept'],y.mean(0))
            sd=x.std(0);np.testing.assert_array_equal(w['scale'],np.where(sd>1e-6,sd,1.));v=(x-w['mean'])/w['scale'];grad=v.T@(v@w['weight']-(y-w['intercept']))/len(x)+float(w['penalty'])*w['weight'];res=float(np.max(abs(grad)));assert res<1e-7
            for split in ('train','validation'):
                pred=((features[split][name]-w['mean'])/w['scale'])@w['weight']+w['intercept'];np.testing.assert_array_equal(w[split+'_goal_seeds'],ids[split]);np.testing.assert_allclose(pred,w[split+'_prediction'],rtol=1e-12,atol=1e-10)
                if split=='validation':
                    row=next(row for row in r['rows'] if row['group']==g and row['features']==name);mse=((pred-targets[split])**2).mean(0);r2=1-mse/np.var(targets[split],axis=0);np.testing.assert_allclose(r2,row['validation_axis_r2'],rtol=1e-12,atol=1e-12);np.testing.assert_allclose(mse,row['validation_axis_mse'],rtol=1e-12,atol=1e-10);assert row['motion_constraint_adequate']==bool(np.all(r2>=.5))
            for seed in np.unique(ids['train']):assert len(np.unique(w['fold_id'][ids['train']==seed]))==1
            goals=np.unique(ids['train']);np.random.default_rng(1365001).shuffle(goals)
            for i,fold in enumerate(np.array_split(goals,5)):assert np.all(w['fold_id'][np.isin(ids['train'],fold)]==i)
            assert row['selected_penalty']==float(w['penalty'])==r['penalties'][int(np.argmin(row['cv_scores']))]
            checks.append(dict(group=g,features=name,normal_equation_residual=res))
    result=dict(status='PASS24_MOTION_PROBE_RECONSTRUCTIONS',checks=checks,report_sha256=sha(d/'report.json'),source_sha256=sha(__file__),scope='Independent feature, metric, final-fit normal-equation and goal-fold checks. CV grid scores generated by fitter; not independently refit.')
    with (d/'acceptance.json').open('x') as f:json.dump(result,f,indent=2);f.write('\n')
    print(result['status'])

if __name__=='__main__':main()
