"""Require all24 bound conditions, independently reconstruct predictions, then compare."""
import argparse,json
from pathlib import Path
import numpy as np
import torch
from analyze_coverage_goals import sha,metrics
from nonlinear_pose_cost import numpy_pose
from adaptation_statistics import CONDITIONS,summarize_matrix


def main():
    p=argparse.ArgumentParser()
    for k in ['evaluations','adapted','frozen','bank','plan','config','holdout-config','output']:p.add_argument('--'+k,required=True)
    a=p.parse_args();bank=Path(a.bank);bm=json.loads((bank/'report.json').read_text());ba=json.loads((bank/'acceptance.json').read_text())
    assert ba['status']=='PASS' and not ba['engineering'] and ba['report_sha256']==sha(bank/'report.json')
    assert ba['verifier_sha256']==sha(Path(__file__).with_name('accept_coverage_poses.py'))
    assert bm['config_sha256']==sha(a.holdout_config) and bm['replica']==0 and not bm['engineering']
    hc=json.loads(Path(a.holdout_config).read_text());assert hc['broad_sampling_seeds']==[1261001,1261002,1261003]
    br=next(v for v in bm['rows'] if v['arm']=='broad');assert br['count']==512
    for name,expected in br['files_sha256'].items():assert sha(bank/'broad'/name)==expected
    truth=dict(np.load(bank/'broad/poses.npz'));assert truth['target'].shape==(512,6) and len(set(truth['source_index']))==512
    values={};provenance=[];training=[]
    for i in range(6):
        run=Path(a.evaluations)/f'job_{i}';r=json.loads((run/'report.json').read_text())
        assert r['status']=='COMPLETE_ADAPTATION_FACTORIAL' and r['index']==i
        assert r['source_sha256']==sha(Path(__file__).with_name('evaluate_readout_adaptation.py'))
        for key,path in [('plan_sha256',a.plan),('config_sha256',a.config),('holdout_config_sha256',a.holdout_config),('bank_report_sha256',bank/'report.json'),('bank_acceptance_sha256',bank/'acceptance.json')]:assert r[key]==sha(path)
        assert [v['condition'] for v in r['rows']]==CONDITIONS
        frozen=Path(a.frozen)/f'job_{i}';fr=json.loads((frozen/'report.json').read_text());fa=json.loads((frozen/'acceptance.json').read_text())
        assert fa['status']=='PASS' and fa['report_sha256']==sha(frozen/'report.json') and fr['index']==i
        assert fa['verifier_sha256']==sha(Path(__file__).with_name('accept_representation_readouts.py'))
        for row in r['rows']:
            condition=row['condition'];stage,mode=condition.rsplit('_',1);pv=row['provenance']
            assert pv['frozen_report_sha256']==sha(frozen/'report.json') and pv['frozen_acceptance_sha256']==sha(frozen/'acceptance.json')
            assert row['file']==condition+'.npz' and row['file_sha256']==sha(run/row['file'])
            if mode=='frozen':
                hp=frozen/stage/'weights.npz';frow=next(v for v in fr['rows'] if v['stage']==stage)
                assert frow['labels']==512 and frow['updates']==2000
                assert sha(hp)==pv['weights_sha256']==frow['files_sha256']['weights.npz'];head=dict(np.load(hp))
            else:
                fit=Path(a.adapted)/f'job_{i}'/stage;ar=json.loads((fit/'report.json').read_text());aa=json.loads((fit/'acceptance.json').read_text())
                assert aa['status']=='PASS' and ar['status']=='FIT_REQUIRES_ACCEPTANCE' and ar['updates']==2000
                assert ar['index']==aa['index']==i and ar['stage']==aa['stage']==stage
                assert ar['config_sha256']==sha(a.config) and ar['source_sha256']==sha(Path(__file__).with_name('fit_readout_adaptation.py'))
                assert aa['report_sha256']==pv['adapted_report_sha256']==sha(fit/'report.json')
                assert pv['adapted_acceptance_sha256']==sha(fit/'acceptance.json')
                assert aa['verifier_sha256']==sha(Path(__file__).with_name('accept_readout_adaptation.py'))
                assert ar['weights_sha256']==pv['weights_sha256']==sha(fit/'weights.pt')
                # Trusted checkpoint generated by this project; includes NumPy norms.
                checkpoint=torch.load(fit/'weights.pt',map_location='cpu',weights_only=False)
                head={k:v.numpy() for k,v in checkpoint['head'].items()};head.update(checkpoint['normalization'])
                training.append(dict(index=i,stage=stage,seconds=ar['elapsed_seconds'],peak_allocated_bytes=ar['peak_allocated_bytes'],gpu=ar['gpu'],train_metrics=aa['metrics']))
            z=dict(np.load(run/row['file']))
            for k in ['target','source_index']:np.testing.assert_array_equal(z[k],truth[k])
            assert z['tokens'].shape==(512,192) and z['prediction'].shape==(512,6)
            assert np.isfinite(z['tokens']).all() and np.isfinite(z['prediction']).all()
            np.testing.assert_allclose(z['prediction'],numpy_pose(z['tokens'],head),rtol=1e-10,atol=1e-9)
            for metric,v in metrics(z['prediction'],truth['target']).items():
                values.setdefault(metric,{c:[] for c in CONDITIONS})[condition].append(v)
        provenance.append(dict(index=i,report_sha256=sha(run/'report.json')))
    results={k:summarize_matrix({c:np.stack(v[c]) for c in CONDITIONS}) for k,v in values.items()}
    result=dict(status='PASS_COMPLETE24_CONDITIONS',backbones=6,images=512,results=results,training=training,provenance=provenance,bank_report_sha256=sha(bank/'report.json'),source_sha256=sha(__file__),statistics_sha256=sha(Path(__file__).with_name('adaptation_statistics.py')),bootstrap=dict(seed=1256901,draws=10000,unit='shared image',interval='percentile95'),primary='pretrained adapted-minus-frozen joint precision',scope='Conditional on six fixed backbones and three512-label pools. All24 conditions checked. Secondary intervals nominal. Equal downstream labels/updates, unequal compute/trainable parameters; pretrained vs initial differs in predictive pretraining data. Shared initial encoders are not independent pretraining seeds. No planning/method novelty claim. Saved heads independently recomputed; test encoding inherits evaluator.')
    with Path(a.output).open('x') as f:f.write(json.dumps(result,indent=2)+'\n')
    print('PASS_COMPLETE24_CONDITIONS')


if __name__=='__main__':main()
